name: create_fabrication_data


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    # only trigger on branches, not on tags
    branches: '**'
  pull_request:
  workflow_call:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_fabrication_outputs:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    # Use the v2_dk6 tag instead of v2_k6 at least until a new release is done.
    # see: https://github.com/INTI-CMNB/KiBot/issues/206
    - uses: INTI-CMNB/KiBot@v2_dk6
      with:
        config: electronics/rpi-pico_to_arduino-nano/rpi-pico_to_arduino-nano.kibot.yaml
        dir: fabrication_data
        schema: electronics/rpi-pico_to_arduino-nano/rpi-pico_to_arduino-nano.kicad_sch
        board: electronics/rpi-pico_to_arduino-nano/rpi-pico_to_arduino-nano.kicad_pcb

    - name: upload results
      uses: actions/upload-artifact@v3
      with:
        name: fabrication_data
        path: fabrication_data
